# Generated by Django 4.0.1 on 2022-01-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockerMetrics',
            fields=[
                ('metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_ip', models.CharField(max_length=50)),
                ('node_hostname', models.CharField(max_length=120)),
                ('container_id', models.CharField(max_length=18)),
                ('container_cpu', models.CharField(max_length=10)),
                ('container_mem', models.CharField(max_length=30)),
                ('container_freemem', models.CharField(max_length=20)),
                ('container_usedmem', models.CharField(max_length=20)),
                ('container_ip', models.CharField(max_length=200)),
                ('datestamp', models.DateField(auto_now_add=True)),
                ('timestamp', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DockerNodes',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_hostname', models.CharField(max_length=120)),
                ('node_ip', models.CharField(max_length=50)),
            ],
        ),
    ]
