# Generated by Django 4.0.1 on 2022-01-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetricsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockermetrics',
            name='container_cpu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dockermetrics',
            name='container_freemem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dockermetrics',
            name='container_mem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dockermetrics',
            name='container_usedmem',
            field=models.IntegerField(),
        ),
    ]
