# Generated by Django 4.0.1 on 2022-01-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetricsApp', '0002_alter_dockermetrics_container_cpu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerNodes',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_ip', models.CharField(max_length=50)),
            ],
        ),
    ]
