# Generated by Django 4.0.1 on 2022-01-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetricsApp', '0003_dockernodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockermetrics',
            name='datestamp',
        ),
        migrations.RemoveField(
            model_name='dockermetrics',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='dockermetrics',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
